info:
  name: get-playlists-chart
  type: http
  seq: 4

http:
  method: GET
  url: "{{api-host}}/chart/{{genre-id}}/playlists?index=0&limit=1"
  params:
    - name: index
      value: "0"
      type: query
    - name: limit
      value: "1"
      type: query
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
