name: Build

permissions:
  pull-requests: write
  contents: write

on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build with Gradle
        uses: ./.github/actions/build-with-gradle
