name: Publish Snapshot

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build with Gradle
        uses: ./.github/actions/build-with-gradle

      - name: Check snapshot version
        id: check-snapshot
        run: |
          if grep -E -q "version\s+=\s+'([0-9]+\.){2}[0-9]+-SNAPSHOT'" build.gradle; then
            echo "has-snapshot=true" >> $GITHUB_OUTPUT
          else
            echo "has-snapshot=false" >> $GITHUB_OUTPUT
          fi

      - name: Write snapshot result to job summary
        run: |
          echo "- \`has-snapshot\`: \`$HAS_SNAPSHOT\`" >> $GITHUB_STEP_SUMMARY
        env:
          HAS_SNAPSHOT: ${{ steps.check-snapshot.outputs.has-snapshot }}

      - name: Publish Snapshot
        if: steps.check-snapshot.outputs.has-snapshot == 'true'
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}
