name: Release Please

on:
  workflow_dispatch:
    inputs:
      release-please:
        description: Execute Release Please Action
        required: true
        type: boolean
        default: false

  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: release-${{ github.ref }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: ./.github/actions/setup-gradle

      - name: Create Release Pull Request
        id: release
        if: github.event_name != 'workflow_dispatch' || inputs.release-please == 'true'
        uses: googleapis/release-please-action@v4

      - name: Publish to Central Repository
        run: ./gradlew build sonar publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload Release Artifacts
        if: ${{ steps.release.outputs.release_created }}
        run: gh release upload "$TAG" build/libs/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.release.outputs.tag_name }}
